version: '3'
services:
  react:
    image: node:8.1.3-alpine
    user: node
    working_dir: /home/node/
    volumes:
      - ./:/home/node:rw
    ports:
      - "3000:3000"
    command: node scripts/start.js
